name: Tests

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      node-modules-cache-hit: ${{ steps.cache-node-modules.outputs.cache-hit }}
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

  test-apps-ui:
    needs: setup
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      actions: read

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Install Playwright Chromium
        run: npx playwright install chromium --with-deps

      - name: Run unit tests with coverage
        run: npm run -w apps/ui coverage

      - name: Run Storybook interaction tests
        run: npm run -w apps/ui test:storybook

      - name: Report coverage to PR
        uses: davelosert/vitest-coverage-report-action@bd52af59d9cd548ea7cd405044d2458042e6d888 # v2.10.0
        with:
          working-directory: ./apps/ui

  test-packages:
    needs: setup
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write
      actions: read

    strategy:
      matrix:
        package: [pathfinding, vectors]

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: "lts/*"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Run unit tests with coverage
        run: npm run -w packages/${{ matrix.package }} coverage

      - name: Report coverage to PR
        uses: davelosert/vitest-coverage-report-action@bd52af59d9cd548ea7cd405044d2458042e6d888 # v2.10.0
        with:
          name: "packages/${{ matrix.package }}"
          working-directory: ./packages/${{ matrix.package }}
